name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  prepare-release:
    name: Setup | Build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            qt-arch: linux_x64
            name: APASSTools-Linux.deb
          - os: windows-latest
            qt-arch: win64_mingw73
            name: APASSTools-Windows.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-${{ matrix.qt-arch }}-QtCache
      - name: Setup | Ninja
        uses: seanmiddleditch/gha-setup-ninja@v1
      - name: Setup | Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: ${{ matrix.qt-arch }}
          cached: ${{ steps.cache.outputs.cache-hit }}
          modules: qtsvg
      - name: Build | CMake
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
      - name: Build | Compile
        run: |
          cd build
          cmake --build .
      - name: Build | Package
        run: |
          cd build
          cmake --build . --target package
      - name: Post Setup | Upload Artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.name }}
          path: build/${{ matrix.name }}

  github-release:
    name: Deploy | Github

    runs-on: ubuntu-latest
    needs: prepare-release

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Artifacts
        uses: actions/download-artifact@v2-preview
      - name: Setup | Changelog
        run: |
          # Temporary fix for https://github.com/actions/setup-go/issues/14
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
          git-chglog $(git describe --tags) > RELEASE.md
          ls -la
      - name: Deploy | Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: RELEASE.md
          files: |
            APASSTools-Linux.deb/APASSTools-Linux.deb
            APASSTools-Windows.exe/APASSTools-Windows.exe
