name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

        include:
          - os: ubuntu-latest
            artifact-name: APASSTools-Linux.deb
          - os: windows-latest
            artifact-name: APASSTools-Windows.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Setup | Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache.outputs.cache-hit }}
          modules: qtsvg
      - name: Build | CMake
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build | Compile
        run: |
          cd build
          cmake --build .
      - name: Build | Package
        run: |
          cd build
          cmake --build . --target package
      - name: Post Setup | Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: build/${{ matrix.artifact-name }}
