name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        qt-version:
          - 5.12.8 # LTS
          - 5.15.0 # Latest

        include:
          - os: ubuntu-latest
            artifact-name: APASSTools-Linux.deb
            image-magick: ""
          - os: windows-latest
            artifact-name: APASSTools-Windows.exe
            image-magick: choco install imagemagick --yes
          - os: macos-latest
            artifact-name: APASSTools-Darwin.dmg
            image-magick: brew install imagemagick

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-${{ matrix.qt-version }}-QtCache
      - name: Setup | Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version }}
          cached: ${{ steps.cache.outputs.cache-hit }}
          modules: qtsvg
      - name: Setup | ImageMagick
        run: ${{ matrix.image-magick }}
      - name: Build | CMake
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
      - name: Build | Compile
        run: |
          cd build
          cmake --build . --config RelWithDebInfo
      - name: Build | Package
        run: |
          cd build
          cmake --build . --config RelWithDebInfo --target package
      - name: Post Setup | Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: build/${{ matrix.artifact-name }}
