name: CI

on: [push]

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Setup | Ninja
        uses: seanmiddleditch/gha-setup-ninja@v1
      - name: Setup | CMake
        uses: jwlawson/actions-setup-cmake@v1.0
        with:
          github-api-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup | Qt
        uses: jurplel/install-qt-action@v2
        if: contains( matrix.os, 'ubuntu')
        with:
          cached: ${{ steps.cache.outputs.cache-hit }}
          modules: qtsvg
      - name: Setup | Qt
        uses: jurplel/install-qt-action@v2
        if: contains( matrix.os, 'windows')
        with:
          arch: win64_mingw73
          cached: ${{ steps.cache.outputs.cache-hit }}
          modules: qtsvg
      - name: Build | CMake
        run: |
          mkdir build && cd build
          cmake -GNinja ..
      - name: Build | Ninja
        run: |
          cd build
          ninja
      - name: Build | Package
        run: |
          cd build
          ninja package
      - name: Post Setup | Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          path: build/APASSTools-*-*.*
