name: CI

on: [push]

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            qt-arch: linux_x64
            name: APASSTools-Linux.deb

          - os: windows-latest
            qt-arch: win64_mingw73
            name: APASSTools-Windows.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Setup | Ninja
        uses: seanmiddleditch/gha-setup-ninja@v1
      - name: Setup | CMake
        uses: jwlawson/actions-setup-cmake@v1.1
        with:
          github-api-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup | Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: ${{ matrix.qt-arch }}
          cached: ${{ steps.cache.outputs.cache-hit }}
          modules: qtsvg
      - name: Build | CMake
        run: |
          mkdir build && cd build
          cmake -GNinja ..
      - name: Build | Ninja
        run: |
          cd build
          ninja
      - name: Build | Package
        run: |
          cd build
          ninja package
      - name: Post Setup | Upload Artifacts
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.name }}
          path: build/${{ matrix.name }}
