name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Cache
        id: cache
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache
      - name: Setup | CMake
        uses: jwlawson/actions-setup-cmake@v1.0
        with:
          cmake-version: "3.16.x"
          github-api-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup | Qt
        uses: jurplel/install-qt-action@v2.5.0
        with:
          cached: ${{ steps.cache.outputs.cache-hit }}
      - name: Build | CMake
        run: |
          mkdir build && cd build
          cmake -GNinja ..
      - name: Build | Ninja
        run: ninja
      - name: Build | Package
        run: ninja package
