name: Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic:
    name: Semantic

    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
